title: Dairon Medina Caro
description: > 
  Random ramblings from yet another programmer.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dairon.org" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: codeadict
github_username:  codeadict
linkedin_username: codeadict
google_analytics:

disqus:
  shortname: daironmedinablog

sass:
   sass_dir: _sass
   style: compressed

jekyll-minifier:
    preserve_php: false
    remove_spaces_inside_tags: true
    remove_multi_spaces: true
    remove_comments: true
    remove_intertag_spaces: true
    remove_quotes: true
    compress_css: true
    compress_javascript: true
    compress_json: true
    simple_doctype: true
    preserve_line_breaks: false
    simple_boolean_attributes: true
    compress_js_templates: true

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-minifier

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - notebooks/jekyll.py
  - notebooks/jekyll.tpl

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
