markdown: rdiscount
pygments: true
url: http://codeadict.org
exclude: [ README ]
safe: true
lsi: false
excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:            'Dairon Medina'
baseurl:          /

github:
  repo:           https://github.com/codeadict

author:
  name:           'Dairon Medina'
  url:            https://twitter.com/codeadict
