title: Dairon Medina Caro
email: me@dairon.org
description: > 
  Python/Django developer, FLOSS Enthusiast, Erlang/BEAM lover, dad of Arya...

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dairon.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codeadict
github_username:  codeadict
linkedin_username: codeadict
google_analytics:


disqus:
  shortname: daironmedinablog

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - notebooks/jekyll.py
  - notebooks/jekyll.tpl

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
